### ISSUE TITLE
Cannot read property 'Base' of undefined

### ISSUE THREAD

**Issue by ivostoykov** [spatools/generator-durandal#7]
Hi,

generator failed with the mentioned error. Below are versions and output (patched windows 10). Comments/help appreciated. Thank you

```
x:\Projects\_test>node -v
v7.7.2

x:\Projects\_test>npm -v
4.6.1

x:\Projects\_test>yo --version
1.8.5

x:\Programs\admin\nodejs>npm list generator-durandal
x:\Programs\admin\nodejs
`-- generator-durandal@0.1.5

x:\Projects\_test>yo durandal
x:\Programs\admin\nodejs\node_modules\generator-durandal\app\index.js:17
util.inherits(DurandalGenerator, yeoman.generators.Base);
                                                  ^

TypeError: Cannot read property 'Base' of undefined
    at Object.<anonymous> (x:\Programs\admin\nodejs\node_modules\generator-durandal\app\index.js:17:51)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.get [as durandal:app] (x:\Programs\admin\nodejs\node_modules\yo\node_modules\yeoman-environment\lib\store.js:40:23)
    at Store.get (x:\Programs\admin\nodejs\node_modules\yo\node_modules\yeoman-environment\lib\store.js:64:35)

x:\Projects\_test>

```
PS.: I've dived into the problem and found out that after requiring 'yeoman-generator' on line 4 both yeoman.generators and yeoman.Base are undefined. I'm not sure if I'm missing something...

**Comment by SomaticIT** [comment]
Indeed, the module is no actively maintained. 

In new `yeoman generators` the basic syntax to create a **generator** changed.
Now a generator should be declared using the format `module.exports = class extends Generator {}`.

If you are interested, you can contribute to upgrade this **generator** to new Yeoman version.

What do you think ?

Thanks

**Comment by ivostoykov** [comment]
Sorry for the delay. Now I can give it a try to update it to the new Yo version

I did a fork and now it seems working. Might merge it at some point...
